In [20]:
import numpy as np

In [21]:
A= matrix([0.5,0.5])

In [22]:
B = matrix([0,1])

In [23]:
C = matrix([1.5,1.5])

In [24]:
S = matrix([[0.3,0.2],[0.2, 0.3]])

In [48]:
a1 = A-B
a1

matrix([[ 0.5, -0.5]])

In [49]:
temp_a1 =a1.T
temp_a1

matrix([[ 0.5],
        [-0.5]])

In [50]:
inv = np.linalg.inv(s) 
inv

matrix([[ 6., -4.],
        [-4.,  6.]])

In [51]:
temp = np.dot(a1,inv)
temp

matrix([[ 5., -5.]])

In [52]:
temp = np.dot(temp, temp_a1)
temp

matrix([[5.]])

In [53]:
a2 = A-C
a2

matrix([[-1., -1.]])

In [57]:
temp_a2 =a2.T
temp_a2

matrix([[-1.],
        [-1.]])

In [58]:
temp = np.dot(a2,inv)
temp

matrix([[-2., -2.]])

In [41]:
temp_a =a.T
temp_a

matrix([[-1.],
        [-1.]])

In [59]:
temp = np.dot(temp, temp_a2)
temp

matrix([[4.]])