In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("winequality-red.csv",sep=';')

In [5]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [6]:
from sklearn.preprocessing import StandardScaler

In [16]:
features = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']

In [17]:
x = df.loc[:, features].values

In [18]:
y = df.loc[:,['quality']].values

In [19]:
x = StandardScaler().fit_transform(x)

In [20]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2','principle component 3','principle component 4','principle component 5'])

In [21]:
finalDf = pd.concat([principalDf, df[['quality']]], axis = 1)

In [22]:
finalDf

principal component 1  principal component 2  principle component 3  \
0                 -1.619530               0.450950              -1.774454   
1                 -0.799170               1.856553              -0.911690   
2                 -0.748479               0.882039              -1.171394   
3                  2.357673              -0.269976               0.243489   
4                 -1.619530               0.450950              -1.774454   
5                 -1.583707               0.569195              -1.538286   
6                 -1.101464               0.608015              -1.075915   
7                 -2.248708              -0.416835              -0.986837   
8                 -1.086887              -0.308569              -1.518150   
9                  0.654790               1.665207               1.209476   
10                -1.125204               0.860512              -0.772216   
11                 0.654790               1.665207               1.209476   
12                -3.026861               0.493540              -0.220166   
13                 1.538898              -0.235126               0.047506   
14                 1.565268               4.795247               1.415077   
15                 1.621249               4.780070               1.521008   
16                 1.174566               1.142798               2.394313   
17                 2.695205               1.215494              -0.123395   
18                -0.722438               0.504672              -1.747083   
19                 3.335313               0.753669               0.458160   
20                 0.623645               0.440113               0.982175   
21                -0.205985               0.967949               0.454964   
22                 0.696407              -0.396999              -0.255876   
23                 0.053106               0.416543              -0.932431   
24                -0.878555               0.381133               0.071553   
25                -1.164634              -0.610355              -0.567918   
26                -0.239394              -1.194011              -0.998433   
27                 0.696407              -0.396999              -0.255876   
28                -1.735218               0.588796              -1.577092   
29                -1.322372              -0.410407              -1.539174   
...                     ...                    ...                    ...   
1569              -2.402658              -0.980441               0.787579   
1570               0.200516              -1.188454               2.532809   
1571              -1.711604              -1.075779               0.797043   
1572              -0.786748               2.403114               0.515280   
1573              -2.358612              -0.766029               1.372311   
1574               1.379761               2.748401               2.709686   
1575              -0.525054              -1.606826               0.767907   
1576               0.913681              -1.378833               1.333307   
1577              -1.904681              -0.104474               0.205298   
1578              -1.520401              -0.719469              -0.197884   
1579              -2.748798              -0.429453               0.914338   
1580              -0.782223              -1.814659               1.073914   
1581              -2.748798              -0.429453               0.914338   
1582              -3.208133              -0.889483               0.292215   
1583              -0.829943               1.688286               1.347217   
1584              -0.208027              -0.970116               2.186871   
1585              -0.040012              -0.655587               2.042817   
1586              -0.071481               0.014586               2.774059   
1587              -2.523542              -0.414176               0.318027   
1588              -0.972473               0.798040               2.848895   
15

In [23]:
pca.explained_variance_ratio_


array([0.28173931, 0.1750827 , 0.1409585 , 0.11029387, 0.08720837])

In [29]:
import numpy as np
from scipy.linalg import  svd


A = np.mat("2 2 0 ; -1 1 0")
print(A)

print("SVD")
U, s, VT = svd(A)
print("---------U---------")
print(U)
print()
print("---------S---------")
print(s)
print()
print("-------- VT--------")
print(VT)


[[ 2  2  0]
 [-1  1  0]]
SVD
---------U---------
[[-1.00000000e+00 -1.17756934e-16]
 [-1.17756934e-16  1.00000000e+00]]

---------S---------
[2.82842712 1.41421356]

-------- VT--------
[[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
